service: ruby-cep

provider:
  name: aws
  runtime: ruby2.7

plugins:
  - serverless-ruby-package

package:
  include:
    - handler.rb
    - vendor/**

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /{cep}
          method: get
          cors: true
